name: Cat Diabetes Logger
slug: cat_diabetes_logger
description: A logger for diabetic cat on Senvelgo
version: "2026.01.1"

arch:
  - amd64
  - aarch64

startup: services
boot: auto

ingress: true
ingress_port: 8080
panel_title: Cat Diabetes
panel_icon: mdi:cat

homeassistant_api: true

map:
  - addon_config:rw
